name: Linux AArch64 (aarch64-linux-gnu)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Work around the somewhat broken packages in the GitHub Actions Ubuntu 20.04 image.
    # https://github.com/actions/runner-images/issues/4620#issuecomment-981333260
    - name: Work around broken packages
      run: sudo apt-get -y install --allow-downgrades libpcre2-8-0=10.34-7

    - name: Add clang repo
      run: |
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo tee /etc/apt/sources.list.d/clang.list <<LIST
        deb [arch=amd64,arm64] http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main
        deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main
        LIST

    # Installs dependencies, including arm64 libraries (runs `sudo apt-get update` as part of it)
    - name: Install dependencies
      run: Packaging/nix/debian-cross-aarch64-prep.sh --no-gcc

    - name: Install clang-18
      run: |
        sudo apt-get install -yq --no-install-recommends clang-18 lld-18 libc++-18-dev:arm64 \
          libgcc-10-dev-arm64-cross binutils-aarch64-linux-gnu libc++1-18:arm64 libc++abi1-18:arm64 && \
        sudo update-alternatives --install \
          /usr/bin/clang++ clang++ /usr/bin/clang++-18 200 && \
        sudo update-alternatives --install \
          /usr/bin/clang clang /usr/bin/clang-18 200 \
          --slave /usr/bin/lld lld /usr/bin/lld-18 \
          --slave /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-18

    - name: Cache CMake build folder
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ github.workflow }}-v6-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v6-

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{github.event_name == 'release' && 'Release' || 'RelWithDebInfo'}}
      # We set DEVILUTIONX_SYSTEM_LIBFMT=OFF because its soversion changes frequently.
      # We set DEVILUTIONX_SYSTEM_LIBSODIUM=OFF because its soversion changes frequently.
      # We set DEVILUTIONX_SYSTEM_SIMPLEINI=OFF because we require v4.19+, still missing from many distributions.
      # We set DEVILUTIONX_SYSTEM_BZIP2=OFF because Fedora and Debian do not agree on how to link it.
      run: |
        cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE=../CMake/platforms/aarch64-linux-gnu-clang-static-libc++.toolchain.cmake \
          -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=/usr -DCPACK=ON -DDEVILUTIONX_SYSTEM_LIBFMT=OFF \
          -DDEVILUTIONX_SYSTEM_LIBSODIUM=OFF -DDEVILUTIONX_SYSTEM_SIMPLEINI=OFF -DDEVILUTIONX_SYSTEM_BZIP2=OFF && \
        cmake --build build -j $(getconf _NPROCESSORS_ONLN) --target package

    - name: Package
      run: Packaging/nix/LinuxReleasePackaging.sh && mv devilutionx.tar.xz devilutionx-aarch64-linux-gnu.tar.xz

    # AppImage cross-packaging is not implemented yet.
    # - name: Package AppImage
    #   run: Packaging/nix/AppImage.sh && mv devilutionx.appimage devilutionx-aarch64-linux-gnu.appimage

    - name: Upload Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-aarch64-linux-gnu.tar.xz
        path: devilutionx-aarch64-linux-gnu.tar.xz

    # AppImage cross-packaging is not implemented yet.
    # - name: Upload AppImage
    #   if: ${{ !env.ACT }}
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: devilutionx-aarch64-linux-gnu.appimage
    #     path: devilutionx-aarch64-linux-gnu.appimage

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        file: devilutionx-aarch64-linux-gnu.*
        file_glob: true
        overwrite: true

    - name: Clean up artifacts
      run: rm -rf build/_CPack_Packages build/package build/*.deb build/*.rpm build/*.appimage build/*.tar.xz
