name: Linux_x86_64_SDL1

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: >
        sudo apt update &&
        sudo apt install -y cmake file g++ git libfmt-dev libsdl-dev libsodium-dev libpng-dev libbz2-dev rpm smpq

    - name: Cache CMake build folder
      uses: actions/cache@v2
      with:
        path: build
        key: linux-x86_64-sdl1-cmake-v2-${{ github.sha }}
        restore-keys: linux-x86_64-sdl1-cmake-v2-

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF -DCPACK=ON -DUSE_SDL1=ON -DDISCORD_INTEGRATION=ON

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build -j $(nproc) --target package

    - name: Package
      run: Packaging/nix/LinuxReleasePackaging.sh

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx_linux_x86_64_SDL1.tar.xz
        path: devilutionx.tar.xz
