name: Miyoo Mini Release Build

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  miyoo-mini:
    runs-on: ubuntu-22.04
    container: debian:buster-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name:  Install toolchain
      working-directory: ${{github.workspace}}
      run: sudo Packaging/miyoo_mini/setup_toolchain.sh

    - name:  Build
      working-directory: ${{github.workspace}}
      run: >
        source Packaging/miyoo_mini/toolchain_env.sh &&
        Packaging/miyoo_mini/build.sh

    - name: Upload-OnionOS-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx-onion-os.zip
        path: build-miyoo-mini/devilutionx-onion-os.zip

    - name: Upload-miniUI-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx-miniui.zip
        path: build-miyoo-mini/devilutionx-miniui.zip

    - name: Update Release
      if: ${{ github.event_name == 'release' && github.event.action == 'created' && !env.ACT }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build-miyoo-mini/devilutionx-onion-os.zip,build-miyoo-mini/devilutionx-miniui.zip"
        allowUpdates: true
        omitBody: true
        omitName: true
        omitPrereleaseDuringUpdate: true
        token: ${{ secrets.GITHUB_TOKEN }}
