name: Windows_x86

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: >
        sudo apt update &&
        sudo apt install -y cmake gcc-mingw-w64-i686 g++-mingw-w64-i686 pkg-config-mingw-w64-i686 dpkg-dev wget git sudo smpq &&
        sudo Packaging/windows/mingw-prep.sh

    - name: Cache CMake build folder
      uses: actions/cache@v2
      with:
        path: build
        key: windows-x86-cmake-${{ github.sha }}
        restore-keys: windows-x86-cmake-

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -S. -Bbuild -DNIGHTLY_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc.cmake -DDEVILUTIONX_SYSTEM_BZIP2=OFF

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build -j $(nproc) --target package

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx_x86.zip
        path: build/devilutionx.zip
