name: Windows MSVC x64

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Add ccache to path
      # This is where ccache-action places `ccache.exe`, see:
      # https://github.com/hendrikmuhs/ccache-action/blob/657bab9aeb32eb6d913c2e6882efad4bb7536d94/src/restore.ts#L74-L75
      run: Add-Content $env:GITHUB_PATH "$($env:USERPROFILE)\.cargo\bin"

    - name: Install latest CMake
      uses: lukka/get-cmake@latest

    - name: Restore or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: '98f8d00e89fb6a8019c2045cfa1edbe9d92d3405'

    - name: Fetch test data
      run: |
          mkdir build-ninja-vcpkg-debug
          Invoke-WebRequest -Uri "https://github.com/diasurgical/devilutionx-assets/releases/download/v2/spawn.mpq" -OutFile "build-ninja-vcpkg-debug/spawn.mpq" -Resume

    - name: Get CMakePresets.json
      run: cp Packaging/windows/CMakePresets.json .

    - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-vcpkg-debug'
        buildPreset: 'ninja-vcpkg-debug'
        testPreset: 'ninja-vcpkg-debug'

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: devilutionx.exe
        path: build-ninja-vcpkg-debug/devilutionx.exe
